package Interfaz;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author sohaib
 */
public class Config_ extends javax.swing.JPanel {
private int numPalabras;
    public Config_() {
        initComponents();
        this.setSize(500,380);
        this.setLocation(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoLetras = new javax.swing.ButtonGroup();
        GrupoPistas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        SelectNo = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NumPalabras = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BDarDeAlta = new javax.swing.JButton();
        BDarDeBaja = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        SelectCinco = new javax.swing.JRadioButton();
        SelectSeis = new javax.swing.JRadioButton();
        SelectSi = new javax.swing.JRadioButton();
        BotonGuardar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 380));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 380));

        SelectNo.setBackground(null);
        SelectNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SelectNo.setForeground(new java.awt.Color(0, 0, 0));
        SelectNo.setText("NO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Numero de Letras");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Dejar Pistas");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Numero de Palabras");

        NumPalabras.setBackground(null);
        NumPalabras.setForeground(new java.awt.Color(0, 0, 0));
        NumPalabras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumPalabrasKeyTyped(evt);
            }
        });

        jSeparator3.setBackground(null);
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Opciones de Jugador");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        BDarDeAlta.setBackground(null);
        BDarDeAlta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BDarDeAlta.setForeground(new java.awt.Color(0, 0, 0));
        BDarDeAlta.setText("Dar de Alta");

        BDarDeBaja.setBackground(null);
        BDarDeBaja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BDarDeBaja.setForeground(new java.awt.Color(0, 0, 0));
        BDarDeBaja.setText("Dar de baja");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Opciones de Partida");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        SelectCinco.setBackground(null);
        SelectCinco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SelectCinco.setForeground(new java.awt.Color(0, 0, 0));
        SelectCinco.setText("5 Letras");
        SelectCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectCincoActionPerformed(evt);
            }
        });

        SelectSeis.setBackground(null);
        SelectSeis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SelectSeis.setForeground(new java.awt.Color(0, 0, 0));
        SelectSeis.setText("6 Letras");

        SelectSi.setBackground(null);
        SelectSi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SelectSi.setForeground(new java.awt.Color(0, 0, 0));
        SelectSi.setText("SI");

        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(SelectSeis)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(281, 281, 281))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NumPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SelectSi)
                                    .addComponent(SelectNo))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(SelectCinco))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5))
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(304, 304, 304)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BDarDeBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BDarDeAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(BotonGuardar)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BDarDeAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BDarDeBaja)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectCinco)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SelectSeis)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(NumPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectSi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(SelectNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(BotonGuardar)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SelectCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectCincoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectCincoActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
//GRUPO DE BOTONES SOBRE NUM LETRAS
        GrupoLetras.add(SelectCinco);
        GrupoLetras.add(SelectSeis);
        
//GRUPO DE BOTONES SOBRE DAR LAS PISTAS
        GrupoPistas.add(SelectSi);
        GrupoPistas.add(SelectNo);

 //-------------VALORES EN ORDEN PARA METER EN FICHERO-----------------------------------       
//CONDICION PARA SELECCIONAR UNO U OTRO (LETRAS)
        if(SelectCinco.isSelected()){
            System.out.println("->LA PALABRA TENDRA 5 LETRAS");
        }else if(SelectSeis.isSelected()){
            System.out.println("-> LA PALABRA TENDRA 6 LETRAS");
        }else{
            System.out.println("-> NINGUNA SELECCIONADA");
        }
        
//IMPRIMIR Y GUARDAR NUMERO DE PALABRAS
     numPalabras=Integer.parseInt(NumPalabras.getText()); //convertimos el string en int y lo devolvemos (meter en fichero)
     System.out.println("-> Habra: "+numPalabras+" palabras");
     
        //CONDICION PARA SELECCIONAR UNO U OTRO (PISTAS)
        if(SelectSi.isSelected()){
            System.out.println("-> SE CONCEDE LA PISTA");
        }else if(SelectNo.isSelected()){
            System.out.println("-> NO SE CONCEDE LA PISTA");
        }else{
            System.out.println("-> NINGUNA SELECCIONADA");
        }

        
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void NumPalabrasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumPalabrasKeyTyped
        int teclado = evt.getKeyChar(); //detecta presionado del teclado

    boolean numeros = teclado >= 48 && teclado <= 57; //marcar limites de caracter numerico en tabla ASCII
    
 //CONDICION PARA SOLO ADMITIR CARACTERES NUMERICOS (el valor se guarda en el boton de guardar)
    if (!numeros)
    {
        evt.consume(); //ACCIONA LA FUNCION
    }
    
//CONDICION PARA SOLO ADMITIR 0 A 2 DIGITOS 
        if (NumPalabras.getText().length()>=2)
    {
        evt.consume();//ACCIONA LA FUNCION
    }
    
    
        
    }//GEN-LAST:event_NumPalabrasKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BDarDeAlta;
    private javax.swing.JButton BDarDeBaja;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.ButtonGroup GrupoLetras;
    private javax.swing.ButtonGroup GrupoPistas;
    private javax.swing.JTextField NumPalabras;
    private javax.swing.JRadioButton SelectCinco;
    private javax.swing.JRadioButton SelectNo;
    private javax.swing.JRadioButton SelectSeis;
    private javax.swing.JRadioButton SelectSi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
