/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import java.awt.Color;

/**
 *
 * @author sohaib
 */
public class Config extends javax.swing.JPanel {

    /**
     * Creates new form Config
     */
    public Config() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDeConfig = new javax.swing.JPanel();
        NumPalabras = new javax.swing.JTextField();
        DarBajaBoton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        PanelLetraCinco = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        DarAltaBoton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelLetraSeis = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BotonNo = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        BotonSi = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        PanelDeConfig.setBackground(new java.awt.Color(255, 255, 255));
        PanelDeConfig.setPreferredSize(new java.awt.Dimension(500, 380));
        PanelDeConfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NumPalabras.setBackground(new java.awt.Color(153, 153, 153));
        NumPalabras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NumPalabras.setForeground(new java.awt.Color(0, 0, 0));
        NumPalabras.setBorder(null);
        NumPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumPalabrasActionPerformed(evt);
            }
        });
        PanelDeConfig.add(NumPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 110, 20));

        DarBajaBoton.setBackground(new java.awt.Color(255, 255, 255));
        DarBajaBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DarBajaBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DarBajaBotonMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Dar de Baja");

        javax.swing.GroupLayout DarBajaBotonLayout = new javax.swing.GroupLayout(DarBajaBoton);
        DarBajaBoton.setLayout(DarBajaBotonLayout);
        DarBajaBotonLayout.setHorizontalGroup(
            DarBajaBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DarBajaBotonLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        DarBajaBotonLayout.setVerticalGroup(
            DarBajaBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelDeConfig.add(DarBajaBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));
        PanelDeConfig.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 385, 10));

        PanelLetraCinco.setBackground(new java.awt.Color(255, 255, 255));
        PanelLetraCinco.setForeground(new java.awt.Color(0, 0, 0));
        PanelLetraCinco.setPreferredSize(new java.awt.Dimension(104, 20));
        PanelLetraCinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelLetraCincoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelLetraCincoMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("5 letras");

        javax.swing.GroupLayout PanelLetraCincoLayout = new javax.swing.GroupLayout(PanelLetraCinco);
        PanelLetraCinco.setLayout(PanelLetraCincoLayout);
        PanelLetraCincoLayout.setHorizontalGroup(
            PanelLetraCincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLetraCincoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(25, 25, 25))
        );
        PanelLetraCincoLayout.setVerticalGroup(
            PanelLetraCincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        PanelDeConfig.add(PanelLetraCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        DarAltaBoton.setBackground(new java.awt.Color(255, 255, 255));
        DarAltaBoton.setForeground(new java.awt.Color(0, 0, 0));
        DarAltaBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DarAltaBotonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DarAltaBotonMouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Dar de Alta");

        javax.swing.GroupLayout DarAltaBotonLayout = new javax.swing.GroupLayout(DarAltaBoton);
        DarAltaBoton.setLayout(DarAltaBotonLayout);
        DarAltaBotonLayout.setHorizontalGroup(
            DarAltaBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DarAltaBotonLayout.setVerticalGroup(
            DarAltaBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelDeConfig.add(DarAltaBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 93, -1));

        PanelLetraSeis.setBackground(new java.awt.Color(255, 255, 255));
        PanelLetraSeis.setForeground(new java.awt.Color(0, 0, 0));
        PanelLetraSeis.setPreferredSize(new java.awt.Dimension(104, 17));
        PanelLetraSeis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelLetraSeisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelLetraSeisMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("6 letras");

        javax.swing.GroupLayout PanelLetraSeisLayout = new javax.swing.GroupLayout(PanelLetraSeis);
        PanelLetraSeis.setLayout(PanelLetraSeisLayout);
        PanelLetraSeisLayout.setHorizontalGroup(
            PanelLetraSeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLetraSeisLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLetraSeisLayout.setVerticalGroup(
            PanelLetraSeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelDeConfig.add(PanelLetraSeis, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, 20));

        BotonNo.setBackground(new java.awt.Color(255, 255, 255));
        BotonNo.setForeground(new java.awt.Color(0, 0, 0));
        BotonNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonNoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonNoMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("NO");

        javax.swing.GroupLayout BotonNoLayout = new javax.swing.GroupLayout(BotonNo);
        BotonNo.setLayout(BotonNoLayout);
        BotonNoLayout.setHorizontalGroup(
            BotonNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonNoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BotonNoLayout.setVerticalGroup(
            BotonNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        PanelDeConfig.add(BotonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 50, 20));

        BotonSi.setBackground(new java.awt.Color(255, 255, 255));
        BotonSi.setForeground(new java.awt.Color(0, 0, 0));
        BotonSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSiMouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("SI");

        javax.swing.GroupLayout BotonSiLayout = new javax.swing.GroupLayout(BotonSi);
        BotonSi.setLayout(BotonSiLayout);
        BotonSiLayout.setHorizontalGroup(
            BotonSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonSiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BotonSiLayout.setVerticalGroup(
            BotonSiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        PanelDeConfig.add(BotonSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 50, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Ofrecer Letra");
        PanelDeConfig.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Numero de Letras");
        PanelDeConfig.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Numero de Palabras");
        PanelDeConfig.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Opcion de Partida");
        PanelDeConfig.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        PanelDeConfig.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 385, 10));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Opciones de Jugador");
        PanelDeConfig.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        PanelDeConfig.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 110, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDeConfig, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDeConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DarAltaBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DarAltaBotonMouseEntered
        DarAltaBoton.setBackground(Color.GRAY);
    }//GEN-LAST:event_DarAltaBotonMouseEntered

    private void DarAltaBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DarAltaBotonMouseExited
        DarAltaBoton.setBackground(Color.white);
    }//GEN-LAST:event_DarAltaBotonMouseExited

    private void DarBajaBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DarBajaBotonMouseEntered
        DarBajaBoton.setBackground(Color.GRAY);
    }//GEN-LAST:event_DarBajaBotonMouseEntered

    private void DarBajaBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DarBajaBotonMouseExited
        DarBajaBoton.setBackground(Color.white);
    }//GEN-LAST:event_DarBajaBotonMouseExited

    private void NumPalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumPalabrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumPalabrasActionPerformed

    private void PanelLetraCincoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelLetraCincoMouseEntered
        PanelLetraCinco.setBackground(Color.GRAY);
    }//GEN-LAST:event_PanelLetraCincoMouseEntered

    private void PanelLetraSeisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelLetraSeisMouseEntered
        PanelLetraSeis.setBackground(Color.GRAY);
    }//GEN-LAST:event_PanelLetraSeisMouseEntered

    private void PanelLetraSeisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelLetraSeisMouseExited
        PanelLetraSeis.setBackground(Color.white);
    }//GEN-LAST:event_PanelLetraSeisMouseExited

    private void PanelLetraCincoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelLetraCincoMouseExited
        PanelLetraCinco.setBackground(Color.white);
    }//GEN-LAST:event_PanelLetraCincoMouseExited

    private void BotonNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonNoMouseEntered
        BotonNo.setBackground(Color.GRAY);
    }//GEN-LAST:event_BotonNoMouseEntered

    private void BotonNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonNoMouseExited
        BotonNo.setBackground(Color.white);
    }//GEN-LAST:event_BotonNoMouseExited

    private void BotonSiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSiMouseEntered
        BotonSi.setBackground(Color.GRAY);
    }//GEN-LAST:event_BotonSiMouseEntered

    private void BotonSiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSiMouseExited
       BotonSi.setBackground(Color.white);
    }//GEN-LAST:event_BotonSiMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonNo;
    private javax.swing.JPanel BotonSi;
    private javax.swing.JPanel DarAltaBoton;
    private javax.swing.JPanel DarBajaBoton;
    private javax.swing.JTextField NumPalabras;
    private javax.swing.JPanel PanelDeConfig;
    private javax.swing.JPanel PanelLetraCinco;
    private javax.swing.JPanel PanelLetraSeis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
